SYSTEM:
  PROJECT_NAME: ABFNet_TVC
  EXPERIMENT_NAME: abfnet_ferplus
  SAVE_DIR: ./results
DATA:
  DATA_PATH: ./data/FERPlus
  IMG_SIZE: 224
  TIGHTER_CROP_RATIO: 1.0
  BATCH_SIZE: 32
  NUM_WORKERS: 4
  NUM_CLASSES: 7
MODEL:
  NAME: Baiyr
  NUM_CLASSES: 7
  BRIDGE_OUT_CHANNELS: 32
  BRIDGE_USE_MULTI_SCALE_RESIDUAL: true
  BRIDGE_USE_SCALE_WEIGHTING: false
  BACKEND_TYPE: light_conv_se_gap
  LIGHT_BACKEND_HIDDEN_CHANNELS: 96
  MAMBA_EMBED_DIM: 128
  MAMBA_TOKEN_LEN: 49
  MAMBA_NUM_LAYERS: 2
  MAMBA_D_STATE: 16
  MAMBA_D_CONV: 4
  MAMBA_EXPAND: 2
  MAMBA_USE_CLS: false
  MAMBA_VERSION: v4_conv_bi_attn
  MAMBA_LOCAL_KERNEL_SIZE: 3
  USE_AUX_HEAD: false
  BRANCH_A_MODE: a_mobile_single
  BRANCH_B_MODE: b_ir50_multi
  IR50_PRETRAINED_PATH: ./pretrain/ir50.pth
  IR50_FREEZE: true
  IR50_TRAIN_BODY2: true
  IR50_TRAIN_LAST_STAGE: true
  MOBILE_PRETRAINED_PATH: ./pretrain/mobilefacenet_model_best.pth.tar
  MOBILE_FREEZE: true
TRAIN:
  EPOCHS: 200
  LR: 1e-4
  OPTIMIZER: adam
  USE_SAM: true
  SAM_RHO: 0.05
  SAM_ADAPTIVE: false
  LR_SCHEDULER: exponential
  LR_GAMMA: 0.985
  WEIGHT_DECAY: 0.0
  MOMENTUM: 0.9
  IR50_BODY2_LR: 3e-6
  IR50_LAST_STAGE_LR: 1.2e-05
  USE_WEIGHTED_SAMPLER: false
  USE_RANDOM_ERASING: true
  GATE_BALANCE_LAMBDA: 0.0
  LABEL_SMOOTHING: 0.05
  AUX_LOSS_WEIGHT: 0.0
  USE_EMA: false
  EMA_DECAY: 0.999
  EARLY_STOPPING_PATIENCE: 0
  EARLY_STOPPING_MIN_DELTA: 0.0
  DEVICE: cuda
  RESUME: false
  USE_CLASS_WEIGHT: false
TEST:
  EVAL_ONLY: false
  USE_TTA: false
  CHECKPOINT: ./checkpoints/abfnet_ferplus_best.pth
